version: "3.2" # optional since v1.27.0
services:
  redis:
    container_name: "redis-demo"
    image: redis
    command: redis-server --requirepass redis
    ports:
      - "6379:6379"
    volumes:
      - $PWD/redisdata:/data
    environment:
      - REDIS_REPLICATION_MODE=master
